### PR TITLE
Use wrangler2 for running Daphne-Worker locally

### PR DESCRIPTION
**Pull request by cjpatton**
Partially addresses #30. (We should still consider switching to WASI.)
Based on #143 (merge that first).

### CODE REVIEW

**Review by armfazh — APPROVED** [review]

**Comment by cjpatton** [comment]
@armfazh did you get a chance to verify you can run the end-to-end tests?

**Comment by armfazh** [comment]
> did you get a chance to verify you can run the end-to-end tests?

they fail with the following error:

```sh
$ docker-compose up --build --abort-on-container-exit --exit-code-from test 
Building leader
Step 1/20 : FROM rust:1.63-alpine AS builder
 ---> 2b5350fcf82d
Step 2/20 : WORKDIR /tmp/dap_test
 ---> Using cache
 ---> 65b134a446ac
Step 3/20 : RUN apk add --update npm bash g++ openssl-dev
 ---> Running in 60a3173a7a15
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
140209139637064:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919:
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
140209139637064:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919:
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
ERROR: unable to select packages:
  bash (no such package):
    required by: world[bash]
  g++ (no such package):
    required by: world[g++]
  npm (no such package):
    required by: world[npm]
  openssl-dev (no such package):
    required by: world[openssl-dev]
ERROR: Service 'leader' failed to build: The command '/bin/sh -c apk add --update npm bash g++ openssl-dev' returned a non-zero code: 4

```

**Comment by cjpatton** [comment]
I don't expect docker-compose to pass right now, this needs work. Have you had a chance to try out the instructions in daphne_worker_test/README.md?

**Comment by armfazh** [comment]
> Have you had a chance to try out the instructions in daphne_worker_test/README.md?

yes, they work ok on my machine.

**Pull request merged**
